server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://49.234.7.65:3306/SpringBoot_learn?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Syc631017


mybatis-plus:
  mapper-locations: classpath:mapper/${project.database}/**/*.xml,classpath:mapper/*.xml
